// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WADCinema.Areas.Admin.Models.BusinessModel;

namespace WADCinema.Migrations
{
    [DbContext(typeof(CinemaManagementContext))]
    partial class CinemaManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WADCenima.Areas.Admin.Models.Entity.Movie", b =>
                {
                    b.Property<Guid>("MovieId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MovieCast");

                    b.Property<string>("MovieCountry")
                        .HasMaxLength(100);

                    b.Property<DateTime>("MovieDescription");

                    b.Property<string>("MovieDirectors")
                        .HasMaxLength(100);

                    b.Property<string>("MovieName")
                        .HasMaxLength(100);

                    b.Property<string>("MoviePoster");

                    b.Property<int>("MovieTime");

                    b.Property<string>("MovieTrailer");

                    b.Property<string>("MovieWarning")
                        .HasMaxLength(100);

                    b.Property<DateTime>("PremiereDate");

                    b.HasKey("MovieId");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("WADCenima.Areas.Admin.Models.Entity.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NameRole")
                        .HasMaxLength(50);

                    b.Property<int?>("RoleEnum");

                    b.HasKey("RoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("WADCenima.Areas.Admin.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDay");

                    b.Property<string>("Email");

                    b.Property<string>("FullName")
                        .HasMaxLength(100);

                    b.Property<bool>("Gender");

                    b.Property<int>("IdentityCard");

                    b.Property<string>("Password");

                    b.Property<string>("Phone")
                        .HasMaxLength(10);

                    b.Property<int>("RoleId");

                    b.Property<Guid?>("RoleId1");

                    b.Property<string>("UserName")
                        .HasMaxLength(100);

                    b.HasKey("UserId");

                    b.HasIndex("RoleId1");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WADCenima.Areas.Admin.Models.User", b =>
                {
                    b.HasOne("WADCenima.Areas.Admin.Models.Entity.Role", "role")
                        .WithMany("user")
                        .HasForeignKey("RoleId1");
                });
#pragma warning restore 612, 618
        }
    }
}
